language: node_js
node_js:
  - 10
  - 12

before_script:
  - yarn setup
  - yarn build

script:
  - yarn test

after_success:
  - yarn pack

deploy:
#  - provider: pages
#    skip_cleanup: true
#    local_dir: docs/
#    github_token: $GITHUB_TOKEN
#    on:
#      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "smart_pluralisation-*.tgz"
    skip_cleanup: true
    on:
      tags: true
#  - provider: npm
#    skip_cleanup: true
#    email: "youremail@example.com"
#    api_key: $NPM_TOKEN
#    on:
#      tags: true
